name: Run tests on push to develop

on:
  push:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          mkdir temp
          cd temp
          git clone https://github.com/LilyLin395135/Simple-Server.git
          cd Simple-Server
          git checkout develop

      - name: Install dependencies
        run: |
          cd /app/temp/Simple-Server/server
          npm install

      - name: Run tests
        run: |
          cd /app/temp/Simple-Server/server
          npm test
          