name: Deploy to EC2 on push to main
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to ec2
        run: |
          ssh -i ${secrets.EC2_SSH_KEY} ${secrets.EC2_USERNAME}@${secrets.HOST_DNS}
          echo "SSH connection successful!" > $HOME/deployment_test.txt
          cd ec2-user/Developer/Simple-Server/server
          git pull https://github.com/LilyLin395135/Simple-Server.git
          npm install
          pm2 restart all
