name: Lint and Format Check

on:
  push:
    branches:
      - develop

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          mkdir temp
          cd temp
          git clone https://github.com/LilyLin395135/Simple-Server.git
          cd Simple-Server
          git checkout develop

      - name: Install dependencies
        run: |
          cd /app/temp/Simple-Server/server
          npm install

      - name: Run ESLint
        run: |
          cd /app/temp/Simple-Server/server
          npm run lint

      - name: Run Prettier
        run: |
          cd /app/temp/Simple-Server/server
          npm run format
